parameters:
   - name: mathworks.licensing.endpoint
     type: string
     default: ""
pool:
   vmImage: 'Ubuntu 16.04'
steps:
   - task: InstallMATLAB@0
   - task: RunMATLABTests@0
     inputs: 
       sourceFolder: tests
       testResultsJUnit: test-results/results.xml    
