parameters:
   - name: endpoint
     type: string
     default: ""
variables:
   mathworks.licensing.endpoint: ${{ parameters.endpoint }}
pool:
   vmImage: 'Ubuntu 16.04'
steps:
   - task: InstallMATLAB@0
   - task: RunMATLABTests@0
     inputs: 
       sourceFolder: tests
       testResultsJUnit: test-results/results.xml
