name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        salt:
          default:
          required: true
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ github.event.salt }} > /tmp/salt
      
      - name: Upload salt as an artifact
        uses: actions/upload-artifact@v2
        with: 
          name: salt
          path: /tmp/salt      
