name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        endpoint:
          default:
          required: true
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo $MATHWORKS_LICENSING_ENDPOINT
        env: 
          MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.endpoint }}
 
