name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        endpoint:
          default:
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.inputs.endpoint }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Display endpoint for debugging
        run: echo $MATHWORKS_LICENSING_ENDPOINT
      
      - name: Set up MATLAB
        run: wget -qO- --retry-connrefused "https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/ci-install.sh" | sudo -E bash

      - name: Run tests
        run: matlab -batch "assertSuccess(runtests('tests'))"      
