name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        endpoint:
          default:
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #- name: Set up MATLAB
      #  run: wget -qO- --retry-connrefused "https://ssd.mathworks.com/supportfiles/ci/ephemeral-matlab/v0/ci-install.sh" | sudo -E bash
      #  env: 
      #    MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.inputs.endpoint }}

      #- name: Run tests
      #  run: matlab -batch "assertSuccess(runtests('tests'))"
      - name: Display endpoint
        run: echo $MATHWORKS_LICENSING_ENDPOINT
        env: 
          MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.inputs.endpoint }}

        
 
